// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnagnwcrjjtydqcosmrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuYWdud2Nyamp0eWRxY29zbXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTQ1MTYsImV4cCI6MjA2OTI3MDUxNn0.qk97eez3Q-XRonKP710zDGGbULzSZxaYkIKu9iOcv-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});